# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: "Merch4Change"
remote_theme: cepdnaclk/eYY-project-theme
description: "Merchandise for Meaningful Impact - An e-commerce platform empowering non-profits to sell merchandise and fund social causes."
markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
